// progress/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ng-progress-lib-app';
}

<battery-progress percent="80" size="36" color="#983fef" [charging]="true" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="36" color="#da7777" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="36" color="#0088f2" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="70" size="36" color="#f0cb2f" [outlined]="false"></ups-progress>
<ups-progress percent="62" size="36" color="#f0cb2f" [outlined]="false"></ups-progress>
<br/>

<br/><br/><br/><br/>

<div>Centered</div>
<div>24px</div>
<battery-progress percent="80" size="24" color="#983fef" showPercentLabel="true" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="24" color="#da7777" showPercentLabel="true" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="24" color="#0088f2"  showPercentLabel="true" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="24" color="#f0cb2f" showPercentLabel="true"  [outlined]="false"></ups-progress>

<br/>
<div>36px</div>
<battery-progress percent="80" size="36" color="#983fef" showPercentLabel="true" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="36" color="#da7777" showPercentLabel="true" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="36" color="#0088f2"  showPercentLabel="true" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="36" color="#f0cb2f" showPercentLabel="true"  [outlined]="false"></ups-progress>

<br />

<div>48px</div>
<battery-progress percent="80" size="48" color="#983fef" showPercentLabel="true" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="48" color="#da7777" showPercentLabel="true" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="48" color="#0088f2"  showPercentLabel="true" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="48" color="#f0cb2f" showPercentLabel="true"  [outlined]="false"></ups-progress>

<br/><br/><br/><br/>

<div>Right</div>
<div>24px</div>
<battery-progress percent="80" size="24" color="#983fef" showPercentLabel="true" labelPosition="right" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="24" color="#da7777" showPercentLabel="true"  labelPosition="right" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="24" color="#0088f2"  showPercentLabel="true"  labelPosition="right" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="24" color="#f0cb2f" showPercentLabel="true"   labelPosition="right" [outlined]="false"></ups-progress>

<br/>
<div>36px</div>
<battery-progress percent="80" size="36" color="#983fef" showPercentLabel="true"  labelPosition="right" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="36" color="#da7777" showPercentLabel="true"  labelPosition="right" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="36" color="#0088f2"  showPercentLabel="true" labelPosition="right"  ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="36" color="#f0cb2f" showPercentLabel="true"  labelPosition="right"  [outlined]="false"></ups-progress>

<br/>

<div>48px</div>
<battery-progress percent="80" size="48" color="#983fef" showPercentLabel="true" labelPosition="right"  [outlined]="true"></battery-progress>
<heart-progress percent="10" size="48" color="#da7777" showPercentLabel="true"  labelPosition="right" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="48" color="#0088f2"  showPercentLabel="true"  labelPosition="right" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="48" color="#f0cb2f" showPercentLabel="true"  labelPosition="right"  [outlined]="false"></ups-progress>

<br/><br/><br/><br/>

<div>Left</div>
<div>24px</div>
<battery-progress percent="80" size="24" color="#983fef" showPercentLabel="true" labelPosition="left" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="24" color="#da7777" showPercentLabel="true"  labelPosition="left" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="24" color="#0088f2"  showPercentLabel="true"  labelPosition="left" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="24" color="#f0cb2f" showPercentLabel="true"   labelPosition="left" [outlined]="false"></ups-progress>

<br/>
<div>36px</div>
<battery-progress percent="80" size="36" color="#983fef" showPercentLabel="true"  labelPosition="left" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="36" color="#da7777" showPercentLabel="true"  labelPosition="left" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="36" color="#0088f2"  showPercentLabel="true" labelPosition="left"  ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="36" color="#f0cb2f" showPercentLabel="true"  labelPosition="left"  [outlined]="false"></ups-progress>

<br />

<div>48px</div>
<battery-progress percent="80" size="48" color="#983fef" showPercentLabel="true" labelPosition="left"  [outlined]="true"></battery-progress>
<heart-progress percent="10" size="48" color="#da7777" showPercentLabel="true"  labelPosition="left" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="48" color="#0088f2"  showPercentLabel="true"  labelPosition="left" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="48" color="#f0cb2f" showPercentLabel="true"  labelPosition="left"  [outlined]="false"></ups-progress>
<br/><br/><br/><br/>

<div>Bottom</div>
<div>24px</div>
<battery-progress percent="80" size="24" color="#983fef" showPercentLabel="true" labelPosition="bottom" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="24" color="#da7777" showPercentLabel="true"  labelPosition="bottom" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="24" color="#0088f2"  showPercentLabel="true"  labelPosition="bottom" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="24" color="#f0cb2f" showPercentLabel="true"   labelPosition="bottom" [outlined]="false"></ups-progress>

<br/>
<div>36px</div>
<battery-progress percent="80" size="36" color="#983fef" showPercentLabel="true"  labelPosition="bottom" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="36" color="#da7777" showPercentLabel="true"  labelPosition="bottom" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="36" color="#0088f2"  showPercentLabel="true" labelPosition="bottom"  ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="36" color="#f0cb2f" showPercentLabel="true"  labelPosition="bottom"  [outlined]="false"></ups-progress>

<br />

<div>48px</div>
<battery-progress percent="80" size="48" color="#983fef" showPercentLabel="true" labelPosition="bottom"  [outlined]="true"></battery-progress>
<heart-progress percent="10" size="48" color="#da7777" showPercentLabel="true"  labelPosition="bottom" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="48" color="#0088f2"  showPercentLabel="true"  labelPosition="bottom" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="48" color="#f0cb2f" showPercentLabel="true"  labelPosition="bottom"  [outlined]="false"></ups-progress>

<br/><br/><br/><br/>

<div>Top</div>
<div>24px</div>
<battery-progress percent="80" size="24" color="#983fef" showPercentLabel="true" labelPosition="top" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="24" color="#da7777" showPercentLabel="true"  labelPosition="top" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="24" color="#0088f2"  showPercentLabel="true"  labelPosition="top" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="24" color="#f0cb2f" showPercentLabel="true"   labelPosition="top" [outlined]="false"></ups-progress>

<br/>
<div>36px</div>
<battery-progress percent="80" size="36" color="#983fef" showPercentLabel="true"  labelPosition="top" [outlined]="true"></battery-progress>
<heart-progress percent="10" size="36" color="#da7777" showPercentLabel="true"  labelPosition="top" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="36" color="#0088f2"  showPercentLabel="true" labelPosition="top"  ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="36" color="#f0cb2f" showPercentLabel="true"  labelPosition="top"  [outlined]="false"></ups-progress>

<br />

<div>48px</div>
<battery-progress percent="80" size="48" color="#983fef" showPercentLabel="true" labelPosition="top"  [outlined]="true"></battery-progress>
<heart-progress percent="10" size="48" color="#da7777" showPercentLabel="true"  labelPosition="top" [outlined]="false"></heart-progress>
<pie-progress percent="30" size="48" color="#0088f2"  showPercentLabel="true"  labelPosition="top" ring="4" [outlined]="true"></pie-progress>
<ups-progress percent="62" size="48" color="#f0cb2f" showPercentLabel="true"  labelPosition="top"  [outlined]="false"></ups-progress>

// progress/react/demo/src/App.tsx
import React from 'react';
import './App.css';
import { Battery, Ups, Pie, Heart } from '@pxblue/react-progress-icons';

type LabelPosition = undefined | 'top' | 'right' | 'bottom' | 'left';
const positions: LabelPosition[] = [undefined, 'left', 'top', 'right', 'bottom'];
export const App = (): any => (
    <>
        {positions.map((alignment) => (
            <>
                <div style={{ fontSize: 36 }}>{(alignment || 'Center').toUpperCase()}</div>
                {[24, 34, 48, 72].map((size) => (
                    <>
                        <div style={{ fontSize: 24 }}>{`${size}px`}</div>
                        <Battery
                            percent={10}
                            size={size}
                            color="#983fef"
                            showPercentLabel={true}
                            labelPosition={alignment}
                        />
                        <Pie
                            percent={10}
                            size={size}
                            color="#da7777"
                            showPercentLabel={true}
                            labelPosition={alignment}
                        />
                        <Ups
                            percent={10}
                            size={size}
                            color="#0088f2"
                            showPercentLabel={true}
                            labelPosition={alignment}
                        />
                        <Heart
                            percent={54}
                            size={size}
                            color="#f0cb2f"
                            showPercentLabel={true}
                            labelPosition={alignment}
                        />
                        <br />
                    </>
                ))}
                <br />
                <br />
            </>
        ))}
    </>
);
